"use client";
import { CssBaseline, ThemeProvider, createTheme } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./_components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({
    palette: {
      primary: { main: "#e6e6e6", contrastText: "#000" },
      secondary: { main: "#55a4c0", contrastText: "#fff" },
      error: { main: "#ff6d4a" },
    },
  });
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
        <CssBaseline />
      </ThemeProvider>
    </html>
  );
}
